language: node_js
node_js:
  - "4"

services:
  - docker # used to build and push packages to docker (see deploy)

deploy:
  provider: script
  script: bash .travis/docker_push.sh
  on:
    branch: master
