language: node_js
node_js:
  - "12"

services:
  - docker # used to build and push packages to docker (see deploy)

deploy:
  on:
    branch: master
  if: tag IS present  # only deploy tagged commits

  # run script to push to docker
  provider: script
  script: bash .travis/docker-push.sh
