language: node_js
node_js:
  - "12"

services:
  - docker # used to build and push packages to docker (see deploy)

deploy:

  # create docker image
  - provider: script
    on:
      branch: master # deploy from master only
      tags: true  # only deployt tagged changes

    # run script to push to docker
    script: bash .travis/docker-push.sh

  # create GitHub release
  - provider: releases
    cleanup: true
    token: "pzVQCvRp7NMUuOwhB43bAFTmNPatr0cc9vfpYo/U4Zs9fpzA+rIUTElLVzkOYhX6yiPIUq9JoQt1u7wOBFbGf5Kmg+30ovMx0NG9EV4QATGqTSssfJ+5E9hYHNmcVgCh6SYRVZ9u5RtXAsAcXTVN2WOqTKIVzspIJgspMvyUUm7S/YuGNiaDAdRAnLcEkpsf1/w4b7qBja4GvPRnudXXcIbaYaHWYR7dwn7YmwVbGtbXjnjoKKCT7S8t1n9fNMSw1Z8A3xw1nI6L1QL9m9oOXIicJAJGnhKPaTKHEQLwnHi4iGOTzqLJpdQMlNYzbK9l+Ubuw/7F4xdX9gX/TcjloK1L15eY7V220V+UfCCRnX5jbKWuqvNe2N6iOPIqrNlHVckXX4wvamlOa5/lpou2Cu9EM1rGdWjt4gnZG4mXikGUYTziySvC9MxhK9WtQNaJfOUUInLRRj766J6kYzBI/08ar1lnL2m7QBpLwQDkuNZz4pG0yLaXQRqVwvB6JQAb1ArQN5ZvVMfVX1FU5XnKVLnS8DBBtJICwjrwr4ZHJXUrC0+diGr1FVmx/blh6b+IouaSS/PMI9+XVxDaYW8GpybR3ord+lIAlkYR9N8V6RBu7muLXpXGetiVpJrSPX9aaAbQJp7EDMwkSI/oiRP1GooD5tU63DXJxJKEq5rCkNk="
    on:
      branch: master
      tags: true
