language: node_js
node_js:
  - "12"

services:
  - docker # used to build and push packages to docker (see deploy)

deploy:
  on:
    branch: master # deploy from master only
    tags: true  # only deployt tagged changes

  # run script to push to docker
  provider: script
  script: bash .travis/docker-push.sh
